# Generated by Django 6.0.3 on 2026-03-14 14:44

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("operacoes", "0004_solicitacaoedicao"),
    ]

    operations = [
        migrations.AddField(
            model_name="historicaloperacao",
            name="comentario_fora_horario",
            field=models.CharField(
                blank=True, max_length=500, null=True, verbose_name="Comentário fora do horário"
            ),
        ),
        migrations.AddField(
            model_name="historicaloperacao",
            name="registro_fora_horario",
            field=models.BooleanField(default=False, verbose_name="Registrado fora do horário"),
        ),
        migrations.AddField(
            model_name="operacao",
            name="comentario_fora_horario",
            field=models.CharField(
                blank=True, max_length=500, null=True, verbose_name="Comentário fora do horário"
            ),
        ),
        migrations.AddField(
            model_name="operacao",
            name="registro_fora_horario",
            field=models.BooleanField(default=False, verbose_name="Registrado fora do horário"),
        ),
    ]
