# Generated by Django 6.0.3 on 2026-03-16 20:06

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("operacoes", "0009_userprofile"),
    ]

    operations = [
        migrations.AddField(
            model_name="historicaloperacao",
            name="observacao",
            field=models.TextField(blank=True, null=True, verbose_name="Observação"),
        ),
        migrations.AddField(
            model_name="operacao",
            name="observacao",
            field=models.TextField(blank=True, null=True, verbose_name="Observação"),
        ),
    ]
